<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'name' => 'required|max:255|min:3',
            'code' => 'required|numeric',
            'description' => 'required|min:6',
            'image' => 'mimes:jpg,png',
            'price' => 'required|min:1|max:300',
            'count' => 'required|min:0|max:300',
        ];
        if ($this->route()->named('admin.product.store')){
            $rules['image'] = 'required|mimes:jpg,png';
            $rules['category_id'] = 'required|max:255|min:1';

        }
        return  $rules;
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
